# Generated by Django 6.1.1 on 2026-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQbGYVbviHVkwr-Rpa26oQwYCRA2UdVO793PYeAA5p7AuF8eeV7IWtaNRh4tWGsx3SVcbMvoiGdL3grfL780vY6VuFQga1GlKgxSJeXCd424w91rmObZ8noukqelhYc7zVr98A84Q&usqp=CAc'),
            preserve_default=False,
        ),
    ]
