# Generated by Django 6.1.1 on 2026-09-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
