# Generated by Django 6.1.1 on 2026-09-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_mensagem', models.TextField()),
                ('data_criaçao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
