# Generated by Django 6.1.1 on 2026-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('empresa', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('assunto', models.CharField(choices=[('projeto', 'Quero iniciar um projeto'), ('squad', 'Quero montar um squad'), ('legado', 'Tenho um sistema antigo para modernizar'), ('outro', 'Outro assunto')], default='projeto', max_length=20, verbose_name='assunto')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('respondido', models.BooleanField(default=False, verbose_name='respondido')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
